name: Build and push Docker image

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: zeitmeister
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Pull Docker image
        run: docker pull zeitmeister/da-playlist:latest
      - name: Copy secret to file
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with: 
          name: "header-auth.json"
          json: ${{ secrets.AUTH }}
      - name: Copy file to Docker container
        run: docker cp header-auth.json da-playlist-container:/code/header-auth.json 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/da-playlist:latest

