env:
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  DOCKERHUB_USERNAME: zeitmeister
  HEADER_AUTH_JSON2: YOMAMAMAMABAHAMAS

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          password: ${{ env.DOCKERHUB_PASSWORD }}
          username: ${{ env.DOCKERHUB_USERNAME }}
      - name: Pull Docker image
        run: docker pull zeitmeister/da-playlist:latest
      - id: create-json
        name: Copy secret to file
        uses: jsdaniell/create-json@v1.2.2
        with: 
          json: ${{ secrets.AUTH }}
          name: "header-auth.json"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          build-args: |
            "HEADER_AUTH_JSON=${{ secrets.OAUTH }}"
            "PLAYLIST_ENVIRONMENT_BUILD=production"
            "TEST=${{ env.TEST }}"
            "HEADER_AUTH_JSON2=${{ env.HEADER_AUTH_JSON2 }}"
          container: da-playlist-container
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/da-playlist:latest
      - name: Test Environment variables
        run:
          echo "HELLO DUWG"
          ${{ env.TEST.PLAYLIST_ENVIRONMENT_BUILD }}
          echo "HELLO DAWG"


name: Build and push Docker image
on:
  push:
    branches: 
      - "main"
    paths:
      - "version.json"



