name: Build and push Docker image

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: zeitmeister
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  HEADER_AUTH_JSON2: YOMAMAMAMABAHAMAS

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Pull Docker image
        run: docker pull zeitmeister/da-playlist:latest
      - name: Copy secret to file
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with: 
          name: "header-auth.json"
          json: ${{ secrets.AUTH }}
      - name: Set environment variable
        env:
          TEST: "kebabsoes"
        run: | 
          json_object=$(cat header-auth.json)
          json_string=$(echo $json_object | jq -c .)
          encoded_string=$(echo -n $json_object | base64)
          echo "HEADER_AUTH_JSON=$encoded_string" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/da-playlist:latest
          container: da-playlist-container
          build-args: |
            "HEADER_AUTH_JSON=${{ env.HEADER_AUTH_JSON }}"
            "PLAYLIST_ENVIRONMENT_BUILD=production"
            "TEST=${{ env.TEST }}"
            "HEADER_AUTH_JSON2=${{ env.HEADER_AUTH_JSON2 }}"
      - name: Test Environment variables
        run:
          echo "HELLO DUWG"
          ${{ env.TEST.PLAYLIST_ENVIRONMENT_BUILD }}
          ${{ env.HEADER_AUTH_JSON }}
          echo "HELLO DAWG"



