name: Build and push Docker image

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: zeitmeister
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - name: Pull Docker image
        run: docker pull zeitmeister/da-playlist:latest
      - name: Copy secret to file
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with: 
          name: "header-auth.json"
          json: ${{ secrets.AUTH }}
      - name: Set environment variable
        env:
          playlist_environment_build: "production"
        run: | 
          json_object=$(cat header-auth.json)
          json_string=$(echo $json_object | jq -c .)
          echo "HEADER_AUTH_JSON=$json_string" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/da-playlist:latest
          container-name: da-playlist-container
          build-args: |
            HEADER_AUTH_JSON=${{ secrets.AUTH }}
            PLAYLIST_ENVIRONMENT_BUILD=production
      - name: Test Environment variables
        run:
          echo "HELLO DUWG"
          echo ${{ env }}
          echo ${{ env.HEADER_AUTH_JSON }}
          echo "HELLO DAWG"



